# 开发环境
# 服务器配置
server:
  # 端口
  port: 8080

# spring配置信息
spring:
  # 模版引擎配置
  thymeleaf:
      mode: LEGACYHTML5
      cache: false
  # output配置
  output:
    # 是否支持彩色输出(ANSI)
    ansi:
      enabled: always