server:
  port: 8081
spring:
  # SpringBoot2.0.x加入Druid依赖后,不用配置就可以监控数据源情况
  datasource:
    url: jdbc:mysql:///db_fly?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  thymeleaf:
      mode: LEGACYHTML5
      cache: false
  output:
    ansi:
      enabled: always
mybatis:
  mapper-locations: classpath:mappers/*.xml
