server:
  port: 8080

spring:
  # 下面3项是必填项,详情见https://github.com/alibaba/druid/tree/master/druid-spring-boot-starter
  datasource:
    url: jdbc:mysql:///db_fly?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  # 连接池配置可省略,即使用默认配置信息

  thymeleaf:
      mode: LEGACYHTML5
      cache: false

  output:
    ansi:
      enabled: always

mybatis:
  mapper-locations: classpath:mappers/*.xml
