server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql:///database_fly?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

  thymeleaf:
      mode: LEGACYHTML5
      cache: false

  output:
    ansi:
      enabled: always

mybatis:
  mapper-locations: classpath:mappers/*.xml
